import { Kafka } from 'kafkajs';
import { ClientManager } from '../websockets/ClientManager';

export class OrderBookConsumer {
    private kafka = new Kafka({ clientId: 'mdg-ob-consumer', brokers: [process.env.KAFKA_BROKERS || 'localhost:9092'] });
    private consumer = this.kafka.consumer({ groupId: 'mdg-orderbook-group' });

    constructor(private clientManager: ClientManager) {}

    async start() {
        await this.consumer.connect();
        // Consuming snapshots generated by apex/order-matching-engine
        await this.consumer.subscribe({ topic: 'nte.orderbook.snapshots', fromBeginning: false });

        await this.consumer.run({
            eachMessage: async ({ topic, partition, message }) => {
                // TODO: Deserialize Protobuf message
                const snapshot = message.value?.toString(); 
                if (snapshot) {
                    this.clientManager.broadcastOrderBook(snapshot);
                }
            }
        });
    }
}
