import { Kafka } from 'kafkajs';
import { ClientManager } from '../websockets/ClientManager';

export class TradeConsumer {
    private kafka = new Kafka({ clientId: 'mdg-trade-consumer', brokers: [process.env.KAFKA_BROKERS || 'localhost:9092'] });
    private consumer = this.kafka.consumer({ groupId: 'mdg-trade-group' });

    constructor(private clientManager: ClientManager) {}

    async start() {
        await this.consumer.connect();
        // Consuming trades generated by astrophage/order-matching-engine
        await this.consumer.subscribe({ topic: 'nte.trades.matched', fromBeginning: false });

        await this.consumer.run({
            eachMessage: async ({ message }) => {
                const tradeData = message.value?.toString();
                if (tradeData) {
                    this.clientManager.broadcastTrade(tradeData);
                }
            }
        });
    }
}
